In [1]:
import pandas as pd
import os

In [2]:
cities = pd.read_excel("Lior/"+os.listdir("Lior")[5], sheet_name=4)[['שם רשות מקומית','סוג רשות ']]

In [3]:
f = sorted([a for a in os.listdir("Lior/years")])
print(f)
# the link
# c = pd.read_excel(f[4], sheet_name=4)
# c[['שם רשות מקומית','סוג רשות ']]

['2013.xls', '2014.xls', '2015.xls', '2016.xlsx', '2017.xlsx', '2018.xlsx', '2019.xlsx', '2020.xlsx', '2021.xlsx', '2022.xlsx']

# 2013

In [4]:
tab_1_2013 = pd.read_excel("Lior/years/2013.xls",sheet_name=1)
tab_1_2013.iloc[:201,:]

tab_2_2013 = pd.read_excel("Lior/years/2013.xls",sheet_name=2)
tab_2_2013.iloc[:201,:]
tab_2_2013 = tab_2_2013.rename(columns={'שם  הרשות1': 'שם  הרשות'})
tab_2_2013

h1 = pd.merge(tab_2_2013.iloc[:201,:],tab_1_2013.iloc[:201,:],on='שם  הרשות',how='inner')

In [27]:
tab_3_2013 = pd.read_excel("Lior/years/2013.xls",sheet_name=3)
tab_3_2013.iloc[:54,:]['שם הרשות']
tab_4_2013 = pd.read_excel("Lior/years/2013.xls",sheet_name=4)
tab_4_2013 = tab_4_2013.rename(columns={'שם הרשות1': 'שם הרשות'})
tab_4_2013.iloc[:54,:]['שם הרשות']

h2 = pd.merge(tab_4_2013.iloc[:54,:],tab_3_2013.iloc[:54,:],on='שם הרשות',how='inner')

In [29]:
h1_col = h1.columns.str.replace('2013','').str.replace('2012','').str.replace('2006','')
# .replace('2012','')
h2_col = h2.columns.str.replace('2013','').str.replace('2012','').str.replace('2004','')
h2_col

Index(['שם הרשות', 'סמל הרשות _x', 'סך כולל הכנסות של הרשות (אלפי ש"ח) ',
       'סך כולל הכנסות של הרשות - אחוז שינוי ראלי  לעומת ',
       'סה"כ הכנסות של הרשות מהתקציב הרגיל (אלפי ש"ח) ',
       'סה"כ הכנסות של הרשות מהתקציב הרגיל - אחוז שינוי ראלי  לעומת ',
       'הכנסות של הרשות מחינוך (אלפי ש"ח) ',
       'הכנסות של הרשות מחינוך - אחוז שינוי ראלי  לעומת ',
       'הכנסות של הרשות מרווחה (אלפי ש"ח) ',
       'הכנסות של הרשות מרווחה - אחוז שינוי ראלי  לעומת ',
       ...
       'ממוצע תלמידים לכיתה בחטיבות ביניים תשע"ג /13',
       'ממוצע תלמידים לכיתה בבתי ספר תיכוניים  תשע"ג /13',
       'אחוז זכאים לתעודת בגרות מבין תלמידי כיתות יב תשע"ג /13',
       'אחוז זכאים לתעודת בגרות שעמדו בדרישות הסף של האוניברסיטאות מבין תלמידי כיתות יב תשע"ג /13',
       'מדד פריפריאליות  - אשכול: (מ-1 עד 10, 1 הפריפריאלי ביותר)',
       'מדד פריפריאליות  - רמה לפי קבוצת אשכול', 'מדד פריפריאליות  - ערך מדד',
       'מדד פריפריאליות  - דירוג: (מ-1 עד 252, 1 הפריפריאלי ביותר)',
       'מדד פריפריאליות  - דירוג לפי מרכיבי המדד: מדד נגישות פוטנציאלית (מ-1 עד 252, 1 הנגישות הנמוכה ביותר)',
       'מדד פריפריאליות  - דירוג לפי מרכיבי המדד: קרבה לגבול מחוז תל אביב (מ-1 עד 252, 1 המרוחק ביותר)'],
      dtype='object', length=285)

In [40]:
for a, b in zip(h1_col,h2_col):
    print()
    print(a)
    print(b)
    print(a==b)

שם  הרשות
שם הרשות
False

סמל הרשות _x
סמל הרשות _x
True

סך כולל הכנסות של הרשות (אלפי ש"ח)
סך כולל הכנסות של הרשות (אלפי ש"ח)
True

סך כולל הכנסות של הרשות - אחוז שינוי ראלי  לעומת
סך כולל הכנסות של הרשות - אחוז שינוי ראלי  לעומת
True

סה"כ הכנסות של הרשות  מהתקציב הרגיל (אלפי ש"ח)
סה"כ הכנסות של הרשות מהתקציב הרגיל (אלפי ש"ח)
False

סה"כ הכנסות של הרשות  מהתקציב הרגיל - אחוז שינוי ראלי  לעומת
סה"כ הכנסות של הרשות מהתקציב הרגיל - אחוז שינוי ראלי  לעומת
False

הכנסות של הרשות מחינוך (אלפי ש"ח)
הכנסות של הרשות מחינוך (אלפי ש"ח)
True

הכנסות של הרשות מחינוך - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מחינוך - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות מרווחה (אלפי ש"ח)
הכנסות של הרשות מרווחה (אלפי ש"ח)
True

הכנסות של הרשות מרווחה - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מרווחה - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות ממפעל המים (אלפי ש"ח)
הכנסות של הרשות ממפעל המים (אלפי ש"ח)
True

הכנסות של הרשות ממפעל המים - אחוז שינוי ראלי  לעומת
הכנסות של הרשות ממפעל המים - אחוז שינוי ראלי  לעומת
True

הכנסות עצמיות של הרשות (אלפי ש"ח)
הכנסות עצמיות של הרשות (אלפי ש"ח)
True

סה"כ הכנסות עצמיות של הרשות - אחוז שינוי ראלי  לעומת
סה"כ הכנסות עצמיות של הרשות - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות מארנונה (גבייה) (אלפי ש"ח)
הכנסות של הרשות מארנונה (גבייה) (אלפי ש"ח)
True

הכנסות של הרשות מארנונה (גבייה) - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מארנונה (גבייה) - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות מארנונה למגורים (גבייה) (אלפי ש"ח)
הכנסות של הרשות מארנונה למגורים (גבייה) (אלפי ש"ח)
True

הכנסות של הרשות מארנונה למגורים (גבייה) - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מארנונה למגורים (גבייה) - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות מארנונה למגורים  -יחס גבייה ב-% לכלל החיובים
הכנסות של הרשות מארנונה למגורים  -יחס גבייה ב-% לכלל החיובים
True

הכנסות של הרשות מארנונה לא למגורים (גבייה) (אלפי ש"ח)
הכנסות של הרשות מארנונה לא למגורים (גבייה) (אלפי ש"ח)
True

הכנסות עצמיות של הרשות מחינוך (אלפי ש"ח)
הכנסות עצמיות של הרשות מחינוך (אלפי ש"ח)
True

הכנסות עצמיות של הרשות מחינוך - אחוז שינוי ראלי  לעומת
הכנסות עצמיות של הרשות מחינוך - אחוז שינוי ראלי  לעומת
True

הכנסות עצמיות של הרשות מרווחה (אלפי ש"ח)
הכנסות עצמיות של הרשות מרווחה (אלפי ש"ח)
True

הכנסות עצמיות של הרשות מרווחה - אחוז שינוי ראלי  לעומת
הכנסות עצמיות של הרשות מרווחה - אחוז שינוי ראלי  לעומת
True

הכנסות של הרשות ממשרד החינוך (אלפי ש"ח)
הכנסות של הרשות ממשרד החינוך (אלפי ש"ח)
True

הכנסות של הרשות ממשרד הרווחה (אלפי ש"ח)
הכנסות של הרשות ממשרד הרווחה (אלפי ש"ח)
True

סה"כ השתתפות הממשלה בהכנסות  של הרשות (אלפי ש"ח)
סה"כ השתתפות הממשלה בהכנסות  של הרשות (אלפי ש"ח)
True

סה"כ השתתפות הממשלה בהכנסות של הרשות - אחוז שינוי ראלי  לעומת
סה"כ השתתפות הממשלה בהכנסות של הרשות - אחוז שינוי ראלי  לעומת
True

מענק כללי לאיזון (אלפי ש"ח)
מענק כללי לאיזון (אלפי ש"ח)
True

מענק כללי לאיזון - אחוז שינוי ראלי  לעומת
מענק כללי לאיזון - אחוז שינוי ראלי  לעומת
True

מענק מיועד  (אלפי ש"ח)
מענק מיועד  (באלפי ש"ח)
False

מענק מיוחד  (אלפי ש"ח)
מענק מיוחד  (באלפי ש"ח)
False

העברות והכנסות חד-פעמיות לכיסוי גירעון  מצטבר (אלפי ש"ח)
העברות והכנסות חד-פעמיות לכיסוי גירעון  מצטבר (אלפי ש"ח)
True

 העברות והכנסות חד-פעמיות לכיסוי גירעון  מצטבר - אחוז שינוי ראלי  לעומת
 העברות והכנסות חד-פעמיות לכיסוי גירעון  מצטבר - אחוז שינוי ראלי  לעומת
True

מלוות לאיזון (אלפי ש"ח)
מלוות לאיזון (אלפי ש"ח)
True

מלוות לאיזון - אחוז שינוי ראלי  לעומת
מלוות לאיזון - אחוז שינוי ראלי  לעומת
True

סה"כ הכנסות של הרשות מתקציב בלתי רגיל (אלפי ש"ח)
סה"כ הכנסות של הרשות מתקציב בלתי רגיל (אלפי ש"ח)
True

סה"כ הכנסות של הרשות מתקציב בלתי רגיל - אחוז שינוי ראלי  לעומת
סה"כ הכנסות של הרשות מתקציב בלתי רגיל - אחוז שינוי ראלי  לעומת
True

 הכנסות של הרשות מתקציב בלתי רגיל - השתתפות בעלים (אלפי ש"ח)
 הכנסות של הרשות מתקציב בלתי רגיל - השתתפות בעלים (אלפי ש"ח)
True

 הכנסות של הרשות מתקציב בלתי רגיל - השתתפות בעלים - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מתקציב בלתי רגיל - השתתפות בעלים - אחוז שינוי ראלי  לעומת
False

 הכנסות של הרשות  מתקציב בלתי רגיל - השתתפות משרדי ממשלה (אלפי ש"ח)
 הכנסות של הרשות  מתקציב בלתי רגיל - השתתפות משרדי ממשלה (אלפי ש"ח)
True

הכנסות של הרשות מתקציב בלתי רגיל - השתתפות משרדי הממשלה - אחוז שינוי ראלי  לעומת
הכנסות של הרשות מתקציב בלתי רגיל - השתתפות משרדי הממשלה - אחוז שינוי ראלי  לעומת
True

 הכנסות של הרשות מתקציב בלתי רגיל - מלוות (אלפי ש"ח)
 הכנסות של הרשות מתקציב בלתי רגיל - מלוות (אלפי ש"ח)
True

הכנסות של הרשות מתקציב בלתי רגיל - מלוות (אחוז שינוי ראלי  לעומת )
הכנסות של הרשות מתקציב בלתי רגיל - מלוות (אחוז שינוי ראלי  לעומת )
True

סך כולל הוצאות של הרשות (אלפי ש"ח)
סך כולל הוצאות של הרשות (אלפי ש"ח)
True

סך כולל הוצאות של הרשות - אחוז שינוי ראלי  לעומת
סך כולל הוצאות של הרשות - אחוז שינוי ראלי  לעומת
True

סה"כ הוצאות של הרשות בתקציב רגיל (אלפי ש"ח)
סה"כ הוצאות של הרשות בתקציב רגיל (אלפי ש"ח)
True

סה"כ הוצאות של הרשות בתקציב רגיל - אחוז שינוי ראלי  לעומת
סה"כ הוצאות של הרשות בתקציב רגיל - אחוז שינוי ראלי  לעומת
True

הוצאות של הרשות לחינוך (אלפי ש"ח)
הוצאות של הרשות לחינוך (אלפי ש"ח)
True

הוצאות של הרשות לחינוך - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לחינוך - אחוז שינוי ראלי  לעומת
True

הוצאות של הרשות לרווחה (אלפי ש"ח)
הוצאות של הרשות לרווחה (אלפי ש"ח)
True

הוצאות של הרשות לרווחה - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לרווחה - אחוז שינוי ראלי  לעומת
True

הוצאות של הרשות לרכישת מים (אלפי ש"ח)
הוצאות של הרשות לרכישת מים (אלפי ש"ח)
True

הוצאות של הרשות לרכישת מים - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לרכישת מים - אחוז שינוי ראלי  לעומת
True

סה"כ הוצאות של הרשות לעלות עבודה (אלפי ש"ח)
סה"כ הוצאות של הרשות לעלות עבודה (אלפי ש"ח)
True

סה"כ הוצאות של הרשות לעלות עבודה - אחוז שינוי ראלי  לעומת
סה"כ הוצאות של הרשות לעלות עבודה - אחוז שינוי ראלי  לעומת
True

 הוצאות של הרשות לעלות עבודה לחינוך (אלפי ש"ח)
 הוצאות של הרשות לעלות עבודה לחינוך (אלפי ש"ח)
True

הוצאות של הרשות לעלות עבודה לחינוך - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לעלות עבודה לחינוך - אחוז שינוי ראלי  לעומת
True

 הוצאות של הרשות לעלות עבודה לרווחה (אלפי ש"ח)
 הוצאות של הרשות לעלות עבודה לרווחה (אלפי ש"ח)
True

הוצאות של הרשות לעלות עבודה לרווחה - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לעלות עבודה לרווחה - אחוז שינוי ראלי  לעומת
True

הוצאות של הרשות לפעולות (אלפי ש"ח)
הוצאות של הרשות לפעולות (אלפי ש"ח)
True

הוצאות של הרשות לפעולות - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לפעולות - אחוז שינוי ראלי  לעומת
True

הוצאות של הרשות לפירעון מלוות (אלפי ש"ח)
הוצאות של הרשות לפירעון מלוות (אלפי ש"ח)
True

הוצאות של הרשות לפירעון מלוות - אחוז שינוי ראלי  לעומת
הוצאות של הרשות לפירעון מלוות - אחוז שינוי ראלי  לעומת
True

הוצאות מימון של הרשות (אלפי ש"ח)
הוצאות מימון של הרשות (אלפי ש"ח)
True

הוצאות מימון של הרשות - אחוז שינוי ראלי  לעומת
הוצאות מימון של הרשות - אחוז שינוי ראלי  לעומת
True

העברות והוצאות חד-פעמיות (כולל כיסוי גירעון מצטבר) של הרשות (אלפי ש"ח)
העברות והוצאות חד-פעמיות (כולל כיסוי גירעון מצטבר) של הרשות (אלפי ש"ח)
True

העברות והוצאות חד-פעמיות (כולל כיסוי גירעון מצטבר) של הרשות - אחוז שינוי ראלי  לעומת
העברות והוצאות חד-פעמיות (כולל כיסוי גירעון מצטבר) של הרשות - אחוז שינוי ראלי  לעומת
True

הוצאות כלליות, השתתפויות והעברות (אלפי ש"ח)
הוצאות כלליות, השתתפויות והעברות (אלפי ש"ח)
True

הוצאות כלליות, השתתפויות והעברות - אחוז שינוי ראלי  לעומת
הוצאות כלליות, השתתפויות והעברות - אחוז שינוי ראלי  לעומת
True

סה"כ הוצאות של הרשות בתקציב בלתי רגיל (אלפי ש"ח)
סך הכל עומס מלוות לסוף השנה (כולל הפרשי הצמדה)
False

סה"כ הוצאות של הרשות בתקציב בלתי רגיל - אחוז שינוי ראלי  לעומת
סה"כ הוצאות של הרשות בתקציב בלתי רגיל (אלפי ש"ח)
False

סך הכול עומס מלוות לסוף השנה (כולל הפרשי הצמדה)
סה"כ הוצאות של הרשות בתקציב בלתי רגיל - אחוז שינוי ראלי  לעומת
False

הוצאות של הרשות בתקציב בלתי רגיל לעבודות פיתוח (אלפי ש"ח)
הוצאות של הרשות בתקציב בלתי רגיל לעבודות פיתוח (אלפי ש"ח)
True

הוצאות של הרשות בתקציב בלתי רגיל לעבודות פיתוח - אחוז שינוי ראלי  לעומת
הוצאות של הרשות בתקציב בלתי רגיל לעבודות פיתוח - אחוז שינוי ראלי  לעומת
True

 הוצאות של הרשות בתקציב בלתי רגיל להעברת מלוות (אלפי ש"ח)
 הוצאות של הרשות בתקציב בלתי רגיל להעברת מלוות (אלפי ש"ח)
True

 הוצאות של הרשות בתקציב בלתי רגיל להעברת מלוות - אחוז שינוי ראלי  לעומת
 הוצאות של הרשות בתקציב בלתי רגיל להעברת מלוות - אחוז שינוי ראלי  לעומת
True

 הוצאות של הרשות בתקציב בלתי רגיל - אחר (אלפי ש"ח)
 הוצאות של הרשות בתקציב בלתי רגיל - אחר (אלפי ש"ח)
True

הוצאות של הרשות בתקציב בלתי רגיל - אחר - אחוז שינוי ראלי  לעומת
הוצאות של הרשות בתקציב בלתי רגיל - אחר - אחוז שינוי ראלי  לעומת
True

עודף / גירעון בתקציב הרגיל - תקציבי (אלפי ש"ח)
עודף / גירעון בתקציב הרגיל - תקציבי (אלפי ש"ח)
True

עודף / גירעון בתקציב הרגיל - שנתי (אלפי ש"ח)
עודף / גירעון בתקציב הרגיל - שנתי (אלפי ש"ח)
True

עודף/גירעון מצטבר בסוף שנה (אלפי ש"ח)
עודף/גירעון מצטבר בסוף שנה (אלפי ש"ח)
True

חיוב ארנונה סך הכל (שטח באלפי מ"ר)
חיוב ארנונה סך הכל (שטח באלפי מ"ר)
True

חיוב ארנונה למגורים (שטח באלפי מ"ר)
חיוב ארנונה למגורים (שטח באלפי מ"ר)
True

חיוב ארנונה לעסקים (שטח באלפי מ"ר)
חיוב ארנונה לעסקים (שטח באלפי מ"ר)
True

חיוב ארנונה לתעשייה ולמלאכה (שטח באלפי מ"ר)
חיוב ארנונה לתעשייה ולמלאכה (שטח באלפי מ"ר)
True

חיוב ארנונה לבנקים (שטח באלפי מ"ר)
חיוב ארנונה לבנקים (שטח באלפי מ"ר)
True

חיוב ארנונה לבתי מלון (שטח באלפי מ"ר)
חיוב ארנונה לבתי מלון (שטח באלפי מ"ר)
True

חיוב ארנונה למוסדות ולמבנים (שטח באלפי מ"ר)
חיוב ארנונה למוסדות ולמבנים (שטח באלפי מ"ר)
True

חיוב ארנונה לחניונים (שטח באלפי מ"ר)
חיוב ארנונה לחניונים (שטח באלפי מ"ר)
True

חיוב ארנונה לקרקע תפוסה (שטח באלפי מ"ר)
חיוב ארנונה לקרקע תפוסה (שטח באלפי מ"ר)
True

חיוב ארנונה לקרקע חקלאית (שטח באלפי מ"ר)
חיוב ארנונה לקרקע חקלאית (שטח באלפי מ"ר)
True

חיוב ארנונה ליתר סוגי נכס (שטח באלפי מ"ר)
חיוב ארנונה ליתר סוגי נכס (שטח באלפי מ"ר)
True

חיוב ארנונה סך הכל (באלפי ש"ח)
חיוב ארנונה סך הכל (באלפי ש"ח)
True

חיוב ארנונה למגורים (באלפי ש"ח)
חיוב ארנונה למגורים (באלפי ש"ח)
True

חיוב ארנונה לעסקים (באלפי ש"ח)
חיוב ארנונה לעסקים (באלפי ש"ח)
True

חיוב ארנונה לתעשייה ולמלאכה (באלפי ש"ח)
חיוב ארנונה לתעשייה ולמלאכה (באלפי ש"ח)
True

חיוב ארנונה לבנקים (באלפי ש"ח)
חיוב ארנונה לבנקים (באלפי ש"ח)
True

חיוב ארנונה לבתי מלון (באלפי ש"ח)
חיוב ארנונה לבתי מלון (באלפי ש"ח)
True

חיוב ארנונה למוסדות ולמבנים (באלפי ש"ח)
חיוב ארנונה למוסדות ולמבנים (באלפי ש"ח)
True

חיוב ארנונה לחניונים (באלפי ש"ח)
חיוב ארנונה לחניונים (באלפי ש"ח)
True

חיוב ארנונה לקרקע תפוסה (באלפי ש"ח)
חיוב ארנונה לקרקע תפוסה (באלפי ש"ח)
True

חיוב ארנונה לקרקע חקלאית (באלפי ש"ח)
חיוב ארנונה לקרקע חקלאית (באלפי ש"ח)
True

חיוב ארנונה ליתר סוגי נכס (באלפי ש"ח)
חיוב ארנונה ליתר סוגי נכס (באלפי ש"ח)
True

חיוב ארנונה סך הכל (שטח באלפי מ"ר)
חיוב ארנונה סך הכל (שטח באלפי מ"ר)
True

חיוב ארנונה למגורים (שטח באלפי מ"ר)
חיוב ארנונה למגורים (שטח באלפי מ"ר)
True

חיוב ארנונה לעסקים (שטח באלפי מ"ר)
חיוב ארנונה לעסקים (שטח באלפי מ"ר)
True

חיוב ארנונה לתעשייה ולמלאכה (שטח באלפי מ"ר)
חיוב ארנונה לתעשייה ולמלאכה (שטח באלפי מ"ר)
True

חיוב ארנונה לבנקים (שטח באלפי מ"ר)
חיוב ארנונה לבנקים (שטח באלפי מ"ר)
True

חיוב ארנונה לבתי מלון (שטח באלפי מ"ר)
חיוב ארנונה לבתי מלון (שטח באלפי מ"ר)
True

חיוב ארנונה למוסדות ולמבנים (שטח באלפי מ"ר)
חיוב ארנונה למוסדות ולמבנים (שטח באלפי מ"ר)
True

חיוב ארנונה לחניונים (שטח באלפי מ"ר)
חיוב ארנונה לחניונים (שטח באלפי מ"ר)
True

חיוב ארנונה לקרקע תפוסה (שטח באלפי מ"ר)
חיוב ארנונה לקרקע תפוסה (שטח באלפי מ"ר)
True

חיוב ארנונה לקרקע חקלאית (שטח באלפי מ"ר)
חיוב ארנונה לקרקע חקלאית (שטח באלפי מ"ר)
True

חיוב ארנונה ליתר סוגי נכס (שטח באלפי מ"ר)
חיוב ארנונה ליתר סוגי נכס (שטח באלפי מ"ר)
True

חיוב ארנונה סך הכל (באלפי ש"ח)
חיוב ארנונה סך הכל (באלפי ש"ח)
True

חיוב ארנונה למגורים (באלפי ש"ח)
חיוב ארנונה למגורים (באלפי ש"ח)
True

חיוב ארנונה לעסקים (באלפי ש"ח)
חיוב ארנונה לעסקים (באלפי ש"ח)
True

חיוב ארנונה לתעשייה ולמלאכה (באלפי ש"ח)
חיוב ארנונה לתעשייה ולמלאכה (באלפי ש"ח)
True

חיוב ארנונה לבנקים (באלפי ש"ח)
חיוב ארנונה לבנקים (באלפי ש"ח)
True

חיוב ארנונה לבתי מלון (באלפי ש"ח)
חיוב ארנונה לבתי מלון (באלפי ש"ח)
True

חיוב ארנונה למוסדות ולמבנים (באלפי ש"ח)
חיוב ארנונה למוסדות ולמבנים (באלפי ש"ח)
True

חיוב ארנונה לחניונים (באלפי ש"ח)
חיוב ארנונה לחניונים (באלפי ש"ח)
True

חיוב ארנונה לקרקע תפוסה (באלפי ש"ח)
חיוב ארנונה לקרקע תפוסה (באלפי ש"ח)
True

חיוב ארנונה לקרקע חקלאית (באלפי ש"ח)
חיוב ארנונה לקרקע חקלאית (באלפי ש"ח)
True

חיוב ארנונה ליתר סוגי נכס (באלפי ש"ח)
חיוב ארנונה ליתר סוגי נכס (באלפי ש"ח)
True

Unnamed: 1
סמל הרשות _y
False

סמל הרשות _y
מחוז
False

סוג רשות
מעמד מוניציפלי
False

מחוז
מרחק מגבול מחוז תל אביב (ק"מ)
False

מעמד מוניציפלי
שנת קבלת מעמד מוניציפלי
False

מרחק מגבול מחוז תל אביב (ק"מ) 2004
מספר חברי מועצה
False

שנת קבלת מעמד מוניציפלי
מדד חברתי-כלכלי 2008 - אשכול (מ-1 עד 10, 1 הנמוך ביותר)
False

מספר חברי מועצה
מדד חברתי-כלכלי 2008 - ערך מדד
False

סמל ועדת תכנון ובנייה
מדד חברתי-כלכלי 2008 - דירוג (מ-1 עד 252, 1 הנמוך ביותר)
False

שם ועדת תכנון ובנייה
מדד חברתי-כלכלי 2008 - ממוצע משוקלל של ערכי מדד היישובים במועצה אזורית
False

מדד חברתי-כלכלי 2008 - אשכול (מ-1 עד 10, 1 הנמוך ביותר)
מדד חברתי-כלכלי 2008 - סטיית התקן של ערכי מדד היישובים במועצה אזורית המשוקללת על פי גודל האוכלוסייה
False

מדד חברתי-כלכלי 2008 - ערך מדד
ממוצע המרחקים (ק"מ) 2006
False

מדד חברתי-כלכלי 2008 - דירוג (מ-1 עד 252, 1 הנמוך ביותר)
ממוצע המרחקים - משוקלל (ק"מ) 2006
False

מדד חברתי-כלכלי 2008 - ממוצע משוקלל של ערכי מדד האזורים הסטטיסטיים
סה"כ יישובים במועצה
False

מדד חברתי-כלכלי 2008 - סטיית התקן של ערכי מדד האזורים הסטטיסטיים המשוקללת על פי גודל האוכלוסייה
מושבים (לרבות כפרים שיתופיים)
False

סה"כ  אוכלוסייה בסוף  (אלפים)
מושבים שיתופיים
False

יהודים ואחרים (אחוזים)
קיבוצים
False

יהודים (אחוזים)
יישובים מוסדיים, יהודיים
False

ערבים (אחוזים)
יישובים כפריים אחרים, יהודיים
False

מוסלמים (אחוזים)
יישובים קהילתיים
False

נוצרים (אחוזים)
יישובים מוסדיים, לא-יהודיים
False

דרוזים (אחוזים)
יישובים כפריים אחרים, לא-יהודיים
False

סה"כ גברים בסוף  (אלפים)
יישובים עירוניים, יהודיים 9,000-5,000 תושבים
False

סה"כ נשים בסוף  (אלפים)
יישובים עירוניים, יהודיים 4,999-2,000 תושבים
False

יחס תלות (לאלף תושבים בלתי תלויים)
יישובים עירוניים, מושבים 4,999-2,000 תושבים
False

אחוז בני 4-0  באוכלוסייה בסוף
יישובים עירוניים, מושבים שיתופיים 4,999-2,000 תושבים
False

אחוז בני 9-5  באוכלוסייה בסוף
יישובים עירוניים, קיבוצים 4,999-2,000 תושבים
False

אחוז בני  14-10 באוכלוסייה בסוף
יישובים עירוניים, לא-יהודיים 4,999-2,000 תושבים
False

אחוז בני 19-15  באוכלוסייה בסוף
סה"כ  אוכלוסייה1 בסוף  (אלפים)
False

אחוז בני 29-20 באוכלוסייה בסוף
יהודים ואחרים (אחוזים)
False

אחוז בני 44-30  באוכלוסייה בסוף
יהודים (אחוזים)
False

אחוז בני 59-45  באוכלוסייה בסוף
ערבים (אחוזים)
False

אחוז בני 64-60  באוכלוסייה בסוף
מוסלמים (אחוזים)
False

אחוז בני 65 ומעלה  באוכלוסייה בסוף
נוצרים (אחוזים)
False

אחוז בני 17-0  באוכלוסייה בסוף
דרוזים (אחוזים)
False

אחוז בני 75 ומעלה באוכלוסייה בסוף
סה"כ גברים בסוף  (אלפים)
False

לידות חי
סה"כ נשים בסוף  (אלפים)
False

פטירות
יחס תלות (לאלף תושבים בלתי תלויים)
False

ריבוי טבעי - סה"כ
אחוז בני 4-0  באוכלוסייה בסוף
False

ריבוי טבעי  לאלף תושבים -
אחוז בני 9-5  באוכלוסייה בסוף
False

מאזן הגירה - סה"כ
אחוז בני  14-10 באוכלוסייה בסוף
False

אחוז עולי 1990+ מסך האוכלוסייה
אחוז בני 19-15  באוכלוסייה בסוף
False

אחוז גידול האוכלוסייה שנת  לעומת
אחוז בני 29-20 באוכלוסייה בסוף
False

פטירות תינוקות (ממוצע -2009)
אחוז בני 44-30  באוכלוסייה בסוף
False

שיעור פטירות תינוקות1 לאלף לידות חי -2009
אחוז בני 59-45  באוכלוסייה בסוף
False

השתקעות ראשונה של עולים
אחוז בני 64-60  באוכלוסייה בסוף
False

אחוז עולים בני 17-0 בהשתקעות ראשונה
אחוז בני 65 ומעלה  באוכלוסייה בסוף
False

אחוז עולים בני 44-18 בהשתקעות ראשונה
אחוז בני 17-0  באוכלוסייה בסוף
False

אחוז עולים בני 64-45 בהשתקעות ראשונה
אחוז בני 75 ומעלה באוכלוסייה בסוף
False

אחוז עולים בני 65 ומעלה בהשתקעות ראשונה
לידות חי
False

נכנסים מיישובים אחרים - סה"כ
פטירות
False

נכנסים מיישובים אחרים - גברים
ריבוי טבעי - סה"כ
False

נכנסים מיישובים אחרים - נשים
ריבוי טבעי  לאלף תושבים -
False

נכנסים מיישובים אחרים - עד גיל 14
מאזן הגירה - סה"כ
False

נכנסים מיישובים אחרים - גיל 29-15
אחוז עולי 1990+ מסך האוכלוסייה
False

נכנסים מיישובים אחרים - גיל 64-30
אחוז גידול האוכלוסייה שנת  לעומת
False

נכנסים מיישובים אחרים - גיל 65 ומעלה
פטירות תינוקות (ממוצע -2009)
False

יוצאים ליישובים אחרים - סה"כ
שיעור פטירות תינוקות2 לאלף לידות חי -2009
False

יוצאים ליישובים אחרים - גברים
השתקעות ראשונה של עולים
False

יוצאים ליישובים אחרים - נשים
אחוז עולים בני 17-0 בהשתקעות ראשונה
False

יוצאים ליישובים אחרים - עד גיל 14
אחוז עולים בני 44-18 בהשתקעות ראשונה
False

יוצאים ליישובים אחרים - גיל 29-15
אחוז עולים בני 64-45 בהשתקעות ראשונה
False

יוצאים ליישובים אחרים - גיל 64-30
אחוז עולים בני 65 ומעלה בהשתקעות ראשונה
False

יוצאים ליישובים אחרים - גיל 65 ומעלה
נכנסים מיישובים אחרים - סה"כ
False

מקבלי דמי אבטלה - סה"כ (ממוצע חודשי)
נכנסים מיישובים אחרים - גברים
False

מקבלי דמי אבטלה - גברים  (ממוצע חודשי)
נכנסים מיישובים אחרים - נשים
False

מקבלי הכשרה מקצועית - סה"כ
נכנסים מיישובים אחרים - עד גיל 14
False

גיל ממוצע של מקבלי דמי אבטלה (לא כולל חיילים)
נכנסים מיישובים אחרים - גיל 29-15
False

דמי אבטלה ממוצעים ליום (ש"ח)
נכנסים מיישובים אחרים - גיל 64-30
False

מקבלי קצבאות זקנה ושאירים - סה"כ (סוף שנה)
נכנסים מיישובים אחרים - גיל 65 ומעלה
False

אחוז מקבלי השלמת הכנסה מבין מקבלי קצבאות זקנה ושאירים (סוף שנה)
יוצאים ליישובים אחרים - סה"כ
False

מקבלי גמלת הבטחת הכנסה (נפשות, במשך השנה)
יוצאים ליישובים אחרים - גברים
False

מקבלי גמלאות סיעוד (סוף שנה)
יוצאים ליישובים אחרים - נשים
False

מקבלי גמלאות נכות כללית (סוף שנה)
יוצאים ליישובים אחרים - עד גיל 14
False

מקבלי גמלאות ניידות (סוף שנה)
יוצאים ליישובים אחרים - גיל 29-15
False

מקבלי גמלאות נכות מעבודה ותלויים (סוף שנה)
יוצאים ליישובים אחרים - גיל 64-30
False

מבוטחים בקופת חולים - סה"כ (סוף שנה)
יוצאים ליישובים אחרים - גיל 65 ומעלה
False

אחוז המבוטחים בקופ"ח כללית מתוך סך כל המבוטחים
מקבלי דמי אבטלה - סה"כ (ממוצע חודשי)
False

אחוז המבוטחים בקופ"ח מכבי מתוך סך כל המבוטחים
מקבלי דמי אבטלה - גברים   (ממוצע חודשי)
False

אחוז המבוטחים בקופ"ח מאוחדת מתוך סך כל המבוטחים
מקבלי הכשרה מקצועית - סה"כ
False

אחוז המבוטחים בקופ"ח לאומית מתוך סך כל המבוטחים
גיל ממוצע של מקבלי דמי אבטלה (לא כולל חיילים)
False

סה"כ משפחות של מקבלי קצבאות  בגין ילדים (סוף שנה)
דמי אבטלה ממוצעים ליום (ש"ח)
False

מספר משפחות של מקבלי קצבאות  בגין ילדים עם 2-1 ילדים במשפחה
מקבלי קצבאות זקנה ושאירים - סה"כ
False

מספר משפחות של מקבלי קצבאות  בגין ילדים עם 4-3 ילדים במשפחה
אחוז מקבלי השלמת הכנסה מבין מקבלי קצבאות זקנה ושאירים
False

מספר משפחות של מקבלי קצבאות בגין ילדים עם 5 ילדים ויותר במשפחה
מקבלי גמלת הבטחת הכנסה (נפשות, במשך השנה)
False

סה"כ ילדים שבגינם שולמו קצבאות
מקבלי גמלאות סיעוד (סוף שנה)
False

מספר הילדים שבגינם שולמו קצבאות במשפחות עם 2-1 ילדים
מקבלי גמלאות נכות כללית (סוף שנה)
False

מספר הילדים שבגינם שולמו קצבאות במשפחות עם 4-3 ילדים
מקבלי גמלאות ניידות (סוף שנה)
False

מספר הילדים שבגינם שולמו קצבאות במשפחות עם 5 ילדים ויותר
מקבלי גמלאות נכות מעבודה ותלויים (סוף שנה)
False

שכר ממוצע לחודש של שכירים במשך  (ש"ח)
מבוטחים בקופת חולים - סה"כ (סוף שנה)
False

שכר ממוצע לחודש של גברים שכירים במשך  (ש"ח)
אחוז המבוטחים בקופ"ח כללית מתוך סך כל המבוטחים
False

שכר ממוצע לחודש של נשים שכירות במשך  (ש"ח)
אחוז המבוטחים בקופ"ח מכבי מתוך סך כל המבוטחים
False

אחוז שינוי ראלי לעומת שנה קודמת של שכר ממוצע לחודש של שכירים במשך
אחוז המבוטחים בקופ"ח מאוחדת מתוך סך כל המבוטחים
False

אחוז שינוי ראלי לעומת שנה קודמת של שכר ממוצע לחודש של גברים שכירים במשך
אחוז המבוטחים בקופ"ח לאומית מתוך סך כל המבוטחים
False

אחוז שינוי ראלי לעומת שנה קודמת של שכר ממוצע לחודש של נשים שכירות במשך
סה"כ משפחות של מקבלי קצבאות  בגין ילדים (סוף שנה)
False

מספר השכירים ב-
מספר משפחות של מקבלי קצבאות  בגין ילדים עם 2-1 ילדים במשפחה
False

אחוז השכירים המשתכרים עד שכר מינימום ב-
מספר משפחות של מקבלי קצבאות  בגין ילדים עם 4-3 ילדים במשפחה
False

מספר העצמאים ב-
מספר משפחות של מקבלי קצבאות בגין ילדים עם 5 ילדים ויותר במשפחה
False

הכנסה ממוצעת לחודש של העצמאים ב- (ש"ח)
סה"כ ילדים שבגינם שולמו קצבאות
False

אחוז שינוי ראלי של הכנסה ממוצעת לחודש של העצמאים ב- (לעומת 2011)
מספר הילדים שבגינם שולמו קצבאות במשפחות עם 2-1 ילדים
False

אחוז העצמאים המשתכרים עד מחצית השכר הממוצע ב-
מספר הילדים שבגינם שולמו קצבאות במשפחות עם 4-3 ילדים
False

מדד אי-השוויון - שכירים (מדד ג'יני, 0 שוויון מלא)  ב-
מספר הילדים שבגינם שולמו קצבאות במשפחות עם 5 ילדים ויותר
False

בתי ספר - סה"כ  תשע"ג /13
שכר ממוצע לחודש של שכירים במשך  (ש"ח)
False

בתי ספר יסודיים (כולל חינוך מיוחד)  תשע"ג /13

In [32]:
for i in range(len(h2_col)):
    assert h1_col[i] == h2_col[i]

AssertionError:

In [10]:
# for i in range(h1.shape[1]):
#     print(i)
#     print(h1.columns[i])
#     print(h2.columns[i])

In [77]:
# h1 et h2 same until [:120]

In [11]:
tab_2_2014 = pd.read_excel("Lior/years/2014.xls",sheet_name=2)
tab_2_2014.columns = tab_2_2014.iloc[0,:]
tab_2_2014 = tab_2_2014.iloc[1:202,:]
tab_2_2014

,שם הרשות1,סמל הרשות 2014,"סך כולל הכנסות של הרשות (אלפי ש""ח) 2014",סך כולל הכנסות של הרשות - אחוז שינוי ראלי 2014 לעומת 2013,"סה""כ הכנסות של הרשות מהתקציב הרגיל (אלפי ש""ח) 2014","סה""כ הכנסות של הרשות מהתקציב הרגיל - אחוז שינוי ראלי 2014 לעומת 2013","הכנסות של הרשות מחינוך (אלפי ש""ח) 2014",הכנסות של הרשות מחינוך - אחוז שינוי ראלי 2014 לעומת 2013,"הכנסות של הרשות מרווחה (אלפי ש""ח) 2014",הכנסות של הרשות מרווחה - אחוז שינוי ראלי 2014 לעומת 2013,...,"חיוב ארנונה למשרדים, שירותים ומסחר (באלפי ש""ח) 2014","חיוב ארנונה לתעשייה ולמלאכה (באלפי ש""ח) 2014","חיוב ארנונה לבנקים וחברות ביטוח (באלפי ש""ח) 2014","חיוב ארנונה לבתי מלון (באלפי ש""ח) 2014","חיוב ארנונה לחניונים (באלפי ש""ח) 2014","חיוב ארנונה לקרקע תפוסה (באלפי ש""ח) 2014","חיוב ארנונה לקרקע תפוסה במפעל עתיר שטח (באלפי ש""ח) 2014","חיוב ארנונה לאדמה חקלאית (באלפי ש""ח) 2014","חיוב ארנונה למבנה חקלאי (באלפי ש""ח) 2014","חיוב ארנונה ליתר סוגי נכס (באלפי ש""ח) 2014"
1,אום אל-פחם,2710,280445,-9.7,252634,-3.2,129046,-2.6,27282,2.8,...,9563,2904,791,-,61,401,-,-,-,3573
2,אופקים,0031,164465,2.9,136246,-1,22608,-0.1,18861,9.1,...,4898,7036,1549,-,-,769,-,29,-,1285
3,אור יהודה,2400,257091,-3.4,235902,3,41402,1.7,27945,3.1,...,36894,23006,4249,-,2999,2520,-,108,-,4376
4,אור עקיבא,1020,143964,13.8,130561,16.1,24875,6.2,12672,9.8,...,7647,11021,847,-,280,3220,-,-,-,-
5,אילת,2600,584170,6.2,507907,5.4,109076,0.7,24312,10.1,...,67266,11853,5414,83247,312,40488,-,20,-,2409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,שוהם,1304,168736,-16.1,121912,0,41688,-3.5,3771,5.7,...,6269,112,756,-,95,1556,..,312,-,1069
198,שלומי,0812,53527,-9.3,45633,0.9,9822,2.8,5078,-3.2,...,944,6179,160,473,-,2624,..,106,26,325
199,שעב,0538,39221,-25.6,36950,-15.7,14601,3.4,4017,2.3,...,364,641,-,-,-,89,..,-,-,-
200,תל מונד,0154,93378,4.9,77745,3.1,32709,2.9,5801,-1.4,...,2329,161,947,-,-,1164,..,170,760,352
201,תל שבע,1054,67581,-9.6,61644,2.1,25726,13.8,6817,5.9,...,491,200,-,-,-,126,..,-,-,1090

In [13]:
tab_1_2014 = pd.read_excel("Lior/years/2014.xls",sheet_name=1)
tab_1_2014.columns = tab_1_2014.iloc[0,:]
tab_1_2014 = tab_1_2014.iloc[1:202,:]
tab_1_2014

tab_2_2014 = pd.read_excel("Lior/years/2014.xls",sheet_name=2)
tab_2_2014.columns = tab_2_2014.iloc[0,:]
tab_2_2014 = tab_2_2014.iloc[1:202,:]
tab_2_2014 = tab_2_2014.rename(columns={'שם  הרשות1': 'שם  הרשות'})

h1_2014 = pd.merge(tab_2_2014.iloc[1:202,:],tab_1_2014.iloc[1:202,:],on='שם  הרשות',how='inner')

In [14]:
tab_3_2014 = pd.read_excel("Lior/years/2014.xls",sheet_name=1)
tab_3_2014.columns = tab_3_2014.iloc[0,:]
tab_3_2014 = tab_3_2014.iloc[1:202,:]
tab_3_2014

# tab_4_2014 = pd.read_excel("Lior/years/2014.xls",sheet_name=2)
# tab_4_2014.columns = tab_4_2014.iloc[0,:]
# tab_4_2014 = tab_4_2014.iloc[1:202,:]
# tab_4_2014 = tab_4_2014.rename(columns={'שם  הרשות1': 'שם  הרשות'})

# h1_2014 = pd.merge(tab_4_2014.iloc[1:202,:],tab_3_2014.iloc[1:202,:],on='שם  הרשות',how='inner')

,שם הרשות,סמל הרשות 2014,מחוז 2014,מעמד מוניציפלי 2014,"מרחק מגבול מחוז תל אביב (ק""מ) 2004",שנת קבלת מעמד מוניציפלי,"מרחב ימי, רשויות מקומיות הגובלות בחוף הים",מספר חברי מועצה 2014,סמל ועדת תכנון ובנייה 2014,שם ועדת תכנון ובנייה 2014,...,"שימושי קרקע - יער וחורש - שטח בקמ""ר - 2013",שימושי קרקע - יער וחורש 2013 - אחוז מסך כל שטח שיפוט,"שימושי קרקע - מטעים - שטח בקמ""ר - 2013",שימושי קרקע - מטעים 2013 - אחוז מסך כל שטח שיפוט,"שימושי קרקע - גידול שדה - שטח בקמ""ר - 2013",שימושי קרקע - גידול שדה 2013 - אחוז מסך כל שטח שיפוט,"שימושי קרקע - שטח פתוח אחר - שטח בקמ""ר - 2013",שימושי קרקע - שטח פתוח אחר 2013- אחוז מסך כל שטח שיפוט,אוכלוסייה סוף 2013 - סך הכל אלפים,"צפיפות אוכלוסייה לשטח בנוי למגורים (נפשות לקמ""ר) 2013"
1,אום אל-פחם,2710,חיפה,עירייה,58.6,1984,0,15,354,עירון,...,6.31,24.2,5.69,21.8,0.15,0.6,7.24,27.8,50.6,9134
2,אופקים,0031,הדרום,עירייה,85.8,1995,0,5,601,אופקים,...,0.11,1.1,-,-,1.99,19.4,4.55,44.3,25.1,9843
3,אור יהודה,2400,תל אביב,עירייה,0,1988,0,15,552,אור יהודה - אזור,...,-,-,0.35,5.2,2.03,30.3,1.04,15.7,35.5,16825
4,אור עקיבא,1020,חיפה,עירייה,38.7,2001,0,13,353,שומרון,...,0.63,11.4,0.26,4.7,0.45,8.1,1.63,29.4,16.6,10779
5,אילת,2600,הדרום,עירייה,321.7,1959,0,17,602,אילת,...,-,-,0.6,0.6,0.7,0.7,88.22,89.3,48.1,11935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,שוהם,1304,המרכז,מועצה מקומית,12.4,1993,0,12,421,שוהם,...,0.21,2.9,0.37,5.1,0.45,6.3,3.92,54.4,19.6,11529
198,שלומי,0812,הצפון,מועצה מקומית,120.9,1960,0,9,255,מעלה הגליל,...,0.72,12.2,1.45,24.5,0.42,7.1,1.83,30.9,6.2,7209
199,שעב,0538,הצפון,מועצה מקומית,104.6,1975,0,9,263,שפלת הגליל,...,0.13,2.4,1.22,22.6,2.01,37.2,1.38,25.3,6.4,11034
200,תל מונד,0154,המרכז,מועצה מקומית,14.8,1954,0,11,457,שרונים,...,0.01,0.1,2.16,30.6,1.7,24.1,1.13,16.1,11.4,6994
201,תל שבע,1054,הדרום,מועצה מקומית,95.2,1984,0,11,652,נגב מזרחי,...,-,-,0.05,0.5,4.11,43.6,1.69,17.9,17.5,5319

In [38]:
all_data = pd.DataFrame()
columns_names=list()
for file in f:
    if '2013' in file:
        """good columns"""
    elif '2014' in file:
        
    data = pd.read_excel("Lior/years/"+file,sheet_name=0)
    data['year'] = file[:4]
    data = pd.merge(data,cities,left_on='שם רשות מקומית',right_on='שם רשות מקומית')
data

ValueError: Length of values (4) does not match length of index (249)

In [83]:
cols13 = list()
for i in range(1,5):
    cols13.append(pd.read_excel("Lior/years/2013.xls", sheet_name=i).columns)

In [84]:
cols14 = list()
for i in range(1,5):
    u = pd.read_excel("Lior/years/2014.xls", sheet_name=i)
    u.columns = u.iloc[1,:]
    cols14.append(u.columns)

In [85]:
cols15 = list()
for i in range(1,5):
    u = pd.read_excel("Lior/years/2015.xls", sheet_name=i)
    u.columns = u.iloc[1,:]
    cols15.append(u.columns)

In [61]:
# pd.read_excel("Lior/years/2013.xls",sheet_name=4)
pd.read_excel("Lior/years/2015.xls",sheet_name=0)

,Unnamed: 0,ראו מקרא מתחת ללוח,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,רשויות מקומיות,כלל ארצי1,עיריות - סך הכל,מועצות מקומיות - סך הכל,מועצות אזוריות - סך הכל2,קובץ מעודכן לתאריך 30/07/2017
1,כללי,רשויות - סך הכל 2015,255,NaN,NaN,NaN,NaN
2,NaN,עיריות - סך הכל 2015,76,NaN,NaN,NaN,NaN
3,NaN,מועצות מקומיות - סך הכל 2015,125,NaN,NaN,NaN,NaN
4,NaN,מועצות אזוריות - סך הכל 2015,54,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
247,"5 החל משנת 2015 בוטלו הקצאות המים לתעשייה, הצר...",NaN,NaN,NaN,NaN,NaN,NaN
248,6 נתוני ביצוע תקציב אינם כוללים עיריית טייבה ו...,NaN,NaN,NaN,NaN,NaN,NaN
249,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,NaN,הנתון מעודכן לתאריך 04/05/2017,NaN,NaN,NaN,NaN,NaN
251,NaN,הנתון מעודכן לתאריך 30/07/2017,NaN,NaN,NaN,NaN,NaN

In [113]:
a2022 = pd.read_excel(f[0])
a2022.columns = a2022.iloc[16,:]
a2022=a2022.iloc[17:,:]
print(a2022.shape,pd.merge(a2022,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').shape)
# pd.merge(a2022,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית')
a2018 = pd.read_excel(f[3])
a2018.columns = a2018.iloc[16,:]
a2018=a2018.iloc[17:,:]
print(a2018.shape,pd.merge(a2018,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').shape)
print('MISSING DATA')

(82, 3) (82, 4)
(82, 3) (79, 4)
MISSING DATA

In [114]:
a2015=pd.read_excel(f[5])
a2015.columns = a2015.iloc[16,:]
a2015=a2015.iloc[17:,:]
print(a2015.shape,pd.merge(a2015,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').shape)
print('MISSING DATA')

(82, 3) (79, 4)
MISSING DATA

In [115]:

pd.concat([pd.merge(a2015,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית'),
           pd.merge(a2018,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית'),
           pd.merge(a2022,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית')],axis=0).to_excel(f[3]+'_'+'סוג רשות'+'.xlsx')

In [104]:
b = pd.read_excel(f[1])
b.columns = b.iloc[4,:]
b=b.iloc[5:-4,:]
print(b.shape,pd.merge(b,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').shape)
pd.merge(b,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').to_excel(f[1]+'_'+'סוג רשות'+'.xlsx')

(255, 11) (248, 12)

In [92]:
d=pd.read_excel(f[4])
d.columns=d.iloc[5,:]
d=d.iloc[9:-5,:]
print(d.shape,
pd.merge(d,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').shape)
pd.merge(d,c[['שם רשות מקומית','סוג רשות ']],left_on='שם רשות מקומית',right_on='שם רשות מקומית').to_excel(f[4]+'_'+'סוג רשות'+'.xlsx')

(255, 50) (252, 51)

In [110]:
pd.read_excel(f[5])

      Unnamed: 0 Unnamed: 1 Unnamed: 2
0            NaN        NaN        NaN
1            NaN        NaN        NaN
2            NaN        NaN        NaN
3            NaN        NaN        NaN
4            NaN        NaN        NaN
..           ...        ...        ...
94     רמת השרון       2013       8502
95         רעננה       2013       9678
96         שדרות       2013       8305
97         שפרעם       2013       3854
98  תל אביב -יפו       2013       9875

[99 rows x 3 columns]