In [1]:
import mlflow

ModuleNotFoundError: No module named 'mlflow'

In [8]:
from ML_sup_7_Test_models import *

X,y = load_data("data")

In [12]:
X.iloc[0,:].to_dict()

{'Batch_OGD_name': '2301A',
 'Batch_OGD_date': '2023-01-04',
 'Batch_OGD_Technicien': 'IT',
 'Batch_OGD_KC8_batch': 'K01',
 'Batch_OGD_KC8_masse': 5.0,
 'Batch_OGD_THF_batch': 'to_fill',
 'Batch_OGD_THF_Volume': 500.0,
 'Batch_OGD_Temperature': 0.0,
 'Batch_OGD_Agitation': 230.0,
 'Batch_OGD_heure_debut': '2023-01-04 11:00:00',
 'Batch_OGD_heure_fin': '2023-01-10 00:00:00',
 'Batch_OGD_room_HR': 34.3,
 'Batch_OGD_room_T': 20.0,
 'Batch_OGD_Stock': 0.0,
 'Batch_OGD_Analyses': 1}

In [9]:
data = X.iloc[0,:]
data.drop(index=['Batch_OGD_name', 'Batch_OGD_THF_batch', 'Batch_OGD_Stock'],inplace=True)

/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_3014/1715238561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(index=['Batch_OGD_name', 'Batch_OGD_THF_batch', 'Batch_OGD_Stock'],inplace=True)

In [10]:
clean_data(X)

Donées grandes marées disponibles

/Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/ML_sup_7_Test_models.py:141: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[103.21621622  -1.75         3.35294118   3.35294118 370.54545455
   5.64        22.9047619   22.9047619  103.21621622   4.23076923
 -39.6875     -39.6875     -39.6875     -39.6875    ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[(data[var] < low_fly) | (data[var]> up_fly),var] = data.loc[(data[var] < low_fly) | (data[var]> up_fly), 'month_production'].map(_dict)
/Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/ML_sup_7_Test_models.py:141: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 2.66666667  2.66666667  2.66666667  4.5         4.5         4.5
  6.          6.          6.          1.66666667  1.66666667  1.
  1.57142857  1.57142857  1.57142857  1.57142857  1.57142857  1.57142857
  1.57142857  2.25        2.25        2.25        2.25        2.
  2.          2.         33.          4.5         4.5         4.5
  4.5         4.5         6.          6.          6.          6.
  6.          6.          6.          6.          6.          1.66666667
  1.66666667  1.66666667  1.66666667  1.66666667  1.66666667  1.66666667]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[(data[var] < low_fly) | (data[var]> up_fly),var] = data.loc[(data[var] < low_fly) | (data[var]> up_fly), 'month_production'].map(_dict)

,Batch_OGD_Technicien,Batch_OGD_KC8_batch,Batch_OGD_Temperature,Batch_OGD_Agitation,Batch_OGD_room_HR,Batch_OGD_room_T,Batch_OGD_Analyses,conc_KC8,month_production,day_production_start,days_exfo,exfo_gde_maree
0,IT,2023-K01,27.871429,230.0,34.3,20.0,1,0.010000,1,4,5.0,0.0
1,IT,2023-K01,27.871429,230.0,42.2,21.5,1,0.010000,1,5,5.0,0.0
2,IT,2023-K01,27.871429,230.0,37.5,21.5,0,0.009600,1,6,5.0,0.0
3,CD,2023-K02,27.871429,230.0,42.0,22.0,1,0.010000,1,11,5.0,0.0
4,IT,2023-K02,27.871429,230.0,38.7,21.4,0,0.010000,1,12,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
275,CD,2024-K26,31.000000,230.0,60.0,25.0,1,0.040106,7,11,5.0,0.0
276,JP,2024-K28,30.000000,230.0,54.0,21.0,1,0.040207,7,22,7.0,0.0
277,JP,2024-K28,30.000000,230.0,54.0,21.0,1,0.040122,7,22,7.0,0.0
278,JP,2024-K28,30.000000,230.0,54.0,21.0,1,0.040082,7,22,7.0,0.0
279,JP,2024-K28,30.000000,230.0,54.0,21.0,1,0.040129,7,22,7.0,0.0

In [21]:
type(data)

dict

In [12]:
import requests

headers = {'Supervized-API-Key': '12345678','Content-Type': 'application/json'}
data = {
  "Batch_OGD_name": "2301A",
  "Batch_OGD_date": "2023-01-04",
  "Batch_OGD_Technicien": "IT",
  "Batch_OGD_KC8_batch": "K01",
  "Batch_OGD_KC8_masse": 5.0,
  "Batch_OGD_THF_batch": "to_fill",
  "Batch_OGD_THF_Volume": 500.0,
  "Batch_OGD_Temperature": 0,
  "Batch_OGD_Agitation": 230.0,
  "Batch_OGD_heure_debut": "2023-01-04 11:00:00",
  "Batch_OGD_heure_fin": "2023-01-10 00:00:00",
  "Batch_OGD_room_HR": 34.3,
  "Batch_OGD_room_T": 20.0,
  "Batch_OGD_Stock": 0,
  "Batch_OGD_Analyses": "1"
}
import json
response = requests.post(url="http://127.0.0.1:8003/predict/elasticnet",headers=headers,data=json.dumps(data))

In [13]:
response.content

b'{"pred":1.3029135952533673}'

In [ ]:
# connect to mlflow server
mlflow.set_tracking_uri('http://127.0.0.1:8080')

# load model and preprocessor
model_uri = "runs:/b46da47cde0649ecb2bc43292d977b48/logged_model"
model = mlflow.sklearn.load_model(model_uri)
local_path = mlflow.artifacts.download_artifacts(artifact_uri="runs:/dc7ae6946b33437b98c38447bdd9d140/2025-03-15_preprocessor.pkl")
import joblib
preprocessor = joblib.load(local_path)

# prepare data
X_clean = clean_data(X.iloc[0,:])
X_transfo = preprocessor.transform(pd.DataFrame(X_clean).T)
# preidct
pred = model.predict(X_transfo)
print("predictions",pred)

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
Donées grandes marées disponibles
predictions [1.3029136]

/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(index=['Batch_OGD_name', 'Batch_OGD_THF_batch', 'Batch_OGD_Stock'],inplace=True)
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['conc_KC8'] = data['Batch_OGD_KC8_masse'] / data['Batch_OGD_THF_Volume']
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['conc_KC8'] = data['Batch_OGD_KC8_masse'] / data['Batch_OGD_THF_Volume']
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(index=['Batch_OGD_KC8_masse','Batch_OGD_THF_Volume'],inplace=True)
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[index] = pd.to_datetime(data[index])
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['month_production'] = data['Batch_OGD_date'].month
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['month_production'] = data['Batch_OGD_date'].month
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['day_production_start'] = data['Batch_OGD_date'].day
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['day_production_start'] = data['Batch_OGD_date'].day
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['days_exfo'] = (data['Batch_OGD_heure_fin'] - data['Batch_OGD_heure_debut']).days
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['days_exfo'] = (data['Batch_OGD_heure_fin'] - data['Batch_OGD_heure_debut']).days
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Batch_OGD_KC8_batch'] = str(data.Batch_OGD_date.year) + "-" + data.Batch_OGD_KC8_batch
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["exfo_gde_maree"] =  check_if_within_range(data, gde_marees['date'])
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["exfo_gde_maree"] =  check_if_within_range(data, gde_marees['date'])
/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_11193/2027846136.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(index=datetime_to_remove, inplace=True)

,Batch_OGD_Technicien,Batch_OGD_KC8_batch,Batch_OGD_Temperature,Batch_OGD_Agitation,Batch_OGD_room_HR,Batch_OGD_room_T,Batch_OGD_Analyses,conc_KC8,month_production,day_production_start,days_exfo,exfo_gde_maree
0,IT,2023-K01,0.0,230.0,34.3,20.0,1,0.01,1,4,5,0

array([1.3029136])

In [1]:
from mlflow.tracking import MlflowClient
import joblib


mlflow.set_tracking_uri('http://127.0.0.1:8080')

client = MlflowClient()
run_id = "4060abb9d8f74370b31d8be00bbba29e"  # Your run ID

# Download the preprocessor
preprocessor_local_path = client.download_artifacts(run_id, "2025-03-14_preprocessor.pkl")
print(f"Preprocessor downloaded to: {preprocessor_local_path}")

# Load the preprocessor
preprocessor = joblib.load(preprocessor_local_path)
print("Preprocessor loaded successfully!")

ModuleNotFoundError: No module named 'mlflow'

In [6]:
a={"1":2,"2":4}
a.keys()

dict_keys(['1', '2'])

In [13]:
import mlflow
# mlflow.log_artifact()

In [ ]:
ML_supervized/artifacts_RC/252622912507749433/c64a8ad5f92740f08dd73b6fa37d2edc/artifacts/best_model_on_{date2}

In [ ]:
mlflow.sklearn.load_model()

In [1]:
import mlflow

mlflow.set_tracking_uri('http://127.0.0.1:8080')
# List runs from an experiment
experiment_id = "389636696356469292"  # Replace with your experiment ID
runs = mlflow.search_runs(experiment_id)
print(runs[["run_id", "status", "start_time"]])  # Find your run_id

                             run_id    status                       start_time
0  eee61462c48a418197038a7c77c726af  FINISHED 2025-03-14 15:53:20.196000+00:00
1  dbdff3d5231a4a959400b881e612fb40  FINISHED 2025-03-14 15:53:20.076000+00:00
2  635f3f239980482ca06ac1da0d59c6ce    FAILED 2025-03-14 15:51:09.571000+00:00
3  c6e4aa011c9d4f9f9e74a4bedffbc727  FINISHED 2025-03-14 15:38:25.177000+00:00
4  cff0d93d0c1d4751b0a6a2eb0ef04fb7  FINISHED 2025-03-14 15:38:25.069000+00:00
5  88e5ef54afe64e5d97947670770a87a2  FINISHED 2025-03-14 15:37:53.212000+00:00
6  d0707e14ae994e7899a8d5a23e171594  FINISHED 2025-03-14 15:37:53.079000+00:00

In [5]:
import joblib

# Download and load the preprocessor artifact
preprocessor_artifact_path = "2025-03-14_preprocessor.pkl"
mlflow.artifacts.download_artifacts(run_id="2cc3feda407940848d7624fd0bc0a0bf", artifact_path=preprocessor_artifact_path)
preprocessor = joblib.load(preprocessor_artifact_path)

FileNotFoundError: [Errno 2] No such file or directory: '2025-03-14_preprocessor.pkl'

In [3]:
exp_name = "2025-03-14_Cross_validate_ElasticNet_v1_2"
model_name = "best_model_on_2025-03-14"

In [4]:
model = mlflow.sklearn.load_model(f"models:/{model_name}/latest")

/Applications/anaconda3/envs/ML_Flow/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py:31: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])

FileNotFoundError: [Errno 2] No such file or directory: '/Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/artifacts_RC/389636696356469292/39cab922f7524fcd9b00681d79997ea5/artifacts/MLmodel'

In [7]:
import requests


response = requests.get("http://127.0.0.1:8003/variable_importance")
response.content

b'{"detail":"Not Found"}'