In [1]:
import requests

In [4]:
response = requests.get(f'http://127.0.0.1:8000/matieres_premieres/')

In [8]:
data.MP_nom.unique()

NameError: name 'data' is not defined

In [16]:
import pandas as pd

data = pd.DataFrame(response.json())

# data.loc[data.MP_nom == 'Potassium'].sort_values('MP_id')['MP_ref_fournisseur'].values[-1]

data

,MP_id,MP_nom,MP_codeCW,MP_ref_fournisseur,MP_date_reception,MP_quantite,MP_unite,MP_Analyses
0,3,Potassium,CW_003,x13TX0KUFVYUNy2XVEhL,2023-01-01T00:00:00,721.0,kg,codes_analyses_separated_by_commas
1,4,Potassium,CW_003,YxQGVyvo79BqZPTXAwlJ,2023-01-01T00:00:00,420.0,kg,codes_analyses_separated_by_commas
2,5,Potassium,CW_003,fCEpeE0iooQ8hQ0wwxrJ,2023-01-01T00:00:00,363.0,kg,codes_analyses_separated_by_commas
3,6,Potassium,CW_003,tnpsvS3t8DEObyGJF2vb,2023-01-01T00:00:00,570.0,kg,codes_analyses_separated_by_commas
4,7,Carbon,CW_002,jkMzu9prZwZLsLk58L8G,2023-01-01T00:00:00,997.0,kg,codes_analyses_separated_by_commas
...,...,...,...,...,...,...,...,...
196,199,THF,CW_001,wWKcPE9iH9MnfGNyYF0E,2023-01-01T00:00:00,795.0,L,codes_analyses_separated_by_commas
197,200,Potassium,CW_003,G6lgpTWzuKO9phEGuo0R,2023-01-01T00:00:00,894.0,kg,codes_analyses_separated_by_commas
198,201,Carbon,CW_002,z0VY5E5hvUa46holK4SD,2023-01-01T00:00:00,907.0,kg,codes_analyses_separated_by_commas
199,202,Carbon,CW_002,1azfdqffUEQhdjSPiXpR,2023-01-01T00:00:00,513.0,kg,codes_analyses_separated_by_commas
200,203,THF,CW_001,cTSItmmQ6bsjMLRIAe1I,2023-01-01T00:00:00,887.0,L,codes_analyses_separated_by_commas

In [4]:
response = requests.get(f'http://127.0.0.1:8000/KC8/')


import pandas as pd

_ = pd.DataFrame(response.json())

In [5]:
_

,Batch_KC8_id,Batch_KC8_name,Batch_KC8_date,Batch_KC8_Technicien,Batch_KC8_K_batch,Batch_KC8_C_batch,Batch_KC8_masse,Batch_KC8_Temperature,Batch_KC8_Agitation,Batch_KC8_heure_debut,Batch_KC8_heure_fin,Batch_KC8_room_HR,Batch_KC8_room_T,Batch_KC8_Analyses
0,1,Carbon,2024-02-03T00:00:00,LB,su62fAsdKh7z48KafiUC,26IvLbkH0QbocehMBq8v,300,60.0,300,2024-02-03T12:00:00,2024-02-03T13:00:00,22.0,0.2,codes_analyses_separated_by_commas
1,2,Carbon,2024-09-10T00:00:00,RS,SJaEOTT4KNYjPTIShmre,vB9UFj1B6WRJ6ODa1Pfr,300,50.0,250,2024-09-10T12:00:00,2024-09-10T14:00:00,28.0,0.3,codes_analyses_separated_by_commas
2,3,Carbon,2024-10-27T00:00:00,WL,Zlu6pDsq3GiCtFjwS7hV,AjlIx5FTGaPhWgWAGvap,300,70.0,250,2024-10-27T12:00:00,2024-10-27T14:00:00,23.0,0.2,codes_analyses_separated_by_commas
3,4,Carbon,2024-08-15T00:00:00,WL,x13TX0KUFVYUNy2XVEhL,8HCq0in0hAEcpKS0ehJ0,200,60.0,250,2024-08-15T12:00:00,2024-08-15T14:00:00,30.0,0.2,codes_analyses_separated_by_commas
4,5,Potassium,2023-07-31T00:00:00,TB,su62fAsdKh7z48KafiUC,qX8AcGp0pSYAS8TAmtzd,200,60.0,300,2023-07-31T12:00:00,2023-07-31T13:00:00,20.0,0.3,codes_analyses_separated_by_commas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,197,THF,2023-10-16T00:00:00,TB,YxQGVyvo79BqZPTXAwlJ,QW99NjrNn1s9vzG9EAw8,200,50.0,250,2023-10-16T12:00:00,2023-10-16T14:00:00,24.0,0.1,codes_analyses_separated_by_commas
197,198,THF,2024-10-29T00:00:00,LB,Fc9S2Gv4Qp1iyAAWQxh9,wNRhWrytKM0XC5mBBbN7,200,60.0,250,2024-10-29T12:00:00,2024-10-29T13:00:00,24.0,0.1,codes_analyses_separated_by_commas
198,199,THF,2024-04-28T00:00:00,LC,9KAuqrOKacwwQe5ehmgj,hdPhCrGfxcOfspqZrdZr,300,60.0,250,2024-04-28T12:00:00,2024-04-28T14:00:00,26.0,0.3,codes_analyses_separated_by_commas
199,200,THF,2024-10-19T00:00:00,LB,V79Vm7mn0Ii5xCR4y9vx,rOjGbSk6tYbL0eNd1rgC,300,60.0,300,2024-10-19T12:00:00,2024-10-19T13:00:00,28.0,0.3,codes_analyses_separated_by_commas
200,201,Potassium,2025-01-02T00:00:00,TB,Zlu6pDsq3GiCtFjwS7hV,5x3xJFA2bpuyW0sL8zSL,300,70.0,250,2025-01-02T12:00:00,2025-01-02T15:00:00,29.0,0.3,codes_analyses_separated_by_commas

In [13]:
np.max(KC8_all.Batch_KC8_id)

np.int64(601)

In [24]:
KC8_all.loc[KC8_all.Batch_KC8_id==np.max(KC8_all.Batch_KC8_id),'Batch_KC8_name'].values[0]

'K2337'

In [11]:
KC8_all.loc[199,'Batch_KC8_name']

'K2337'

In [1]:
import datetime
today = datetime.datetime.now()
today.strftime('%d/%m/%y')

'22/01/25'

In [7]:
import numpy as np
response = requests.get(f'http://127.0.0.1:8000/KC8/')
KC8_all = pd.DataFrame(response.json())
KC8_all.iloc[np.max(KC8_all.index),'Batch_KC8_name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types